config/routes.rb
Estator::Application.routes.draw do

  root to: 'pages#home'

  resources :properties, only: [:index, :show, :new, :create] do
    collection do
      get :rentals
      get :for_sale
      get :recent
      get :houses
      get :condos
      get :apartments
    end
  end

  namespace :admin do
    resources :properties, except: :show
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  acts_as_taggable

  # These two were originally tables, but I did not see them changing
  # and it makes the performance quite a bit better if we don't have to 
  # routinely join another table
  STATUS = {
    :for_sale       => 0,
    :for_rent       => 1,
    :not_available  => 2
  }

  TYPE = {
    :apartment      => 0,
    :condo          => 1,
    :house          => 2
  }

  validates :name, presence: true
  validates :property_type, presence: true
  validates :status, presence: true
  validates :price, presence: true
  validates :year_built, presence: true
  validates :square_feet, presence: true
  validates :lot_size, presence: true
  validates :baths, presence: true
  validates :bedrooms, presence: true

  attr_accessible :name, :property_type, :status, :price, :year_built, :square_feet,
                  :lot_size, :baths, :bedrooms, :image_url

  # Scopes for convenience
  scope :recent, -> { where("created_at > '#{1.week.ago.to_s(:db)}'") }
  scope :available, -> { where("status !=  #{STATUS[:not_available]}") }
  scope :rentals, -> { where(status: STATUS[:for_rent]) }
  scope :for_sale, -> { where(status: STATUS[:for_sale]) }
  scope :apartments, -> { where(property_type: TYPE[:apartment]) }
  scope :condos, -> { where(property_type: TYPE[:condo]) }
  scope :houses, -> { where(property_type: TYPE[:house]) }


  # Filtering scopes
  scope :at_least_beds, ->(num) { where("bedrooms >= ?", num) }
  scope :at_least_baths, ->(num) { where("baths >= ?", num) }

  scope :more_expensive_than, ->(num) { where("price > ?", num) }
  scope :cheaper_than, ->(num) { where("price < ?", num) }

  scope :more_sq_ft_than, ->(num) { where("square_feet > ?", num) }
  scope :less_sq_ft_than, ->(num) { where("square_feet < ?", num) }

  scope :more_lot_size_than, ->(num) { where("lot_size > ?", num) }
  scope :less_lot_size_than, ->(num) { where("lot_size < ?", num) }

  scope :newer_than, ->(num) { where("year_built > ?", num) }
  scope :older_than, ->(num) { where("year_built < ?", num) }

end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def create
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :setup_search


  def new
    @property = Property.new

    respond_to do |format|
      format.html { render }
    end
  end

  def create
    @property = Property.new(params[:property])
    success = @property.save

    respond_to do |format|
      format.html do 
        if success
          flash[:notice] = "You have listed this property!"
          redirect_to property_path(@property)
        else
          flash[:error] = "Failed to list property: #{@property.errors.full_messages.to_sentence}"
          render :new
        end
        
      end

      format.json do 
        render json: {property: @property, success: success }
      end
    end
  end

  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html { render }
      format.json { render json: @property }
    end
  end

  def rentals
    @properties = @properties.rentals

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  def for_sale
    @properties = @properties.for_sale
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  def houses
    @properties = @properties.houses
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  def condos
    @properties = @properties.condos
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  def apartments
    @properties = @properties.apartments
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  def recent
    @properties = @properties.recent
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties }
    end
  end

  private

  def setup_search
    # Start with all available properties
    @properties = Property.available
    @search_options = {}

    # Run through each passed param, and call the appropriate scope, building the AR relation

    {
      :beds => :at_least_beds,
      :baths => :at_least_baths,
      :price_min => :more_expensive_than,
      :price_max => :cheaper_than,
      :square_feet_min => :more_sq_ft_than,
      :square_feet_max => :less_sq_ft_than,
      :lot_size_min => :more_lot_size_than,
      :lot_size_max => :less_lot_size_than,
      :year_min => :newer_than,
      :year_max => :older_than,
    }.each do |option, scope|
      if params[option].present?
        # Sets the search options so it can be used to populate the search form
        @search_options[option] = params[option]

        # Dyanmically chains a scope onto the AR relation
        @properties = @properties.send(scope, @search_options[option])
      end
    end

  end
end

app/helpers/admin/properties_helper.rb
module Admin::PropertiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def bed_options_for_select(selected)
    options_for_select({
      '0+' => "0",
      '1+' => "1",
      '2+' => "2",
      '3+' => "3",
      '4+' => "4",
      '5+' => "5",
      '6+' => "6"
    }, selected)
  end

  def bath_options_for_select(selected)
    options_for_select({
      '1+' => "1",
      '1.5+' => "1.5",
      '2+' => "2",
      '3+' => "3",
      '4+' => "4",
      '5+' => "5",
      '6+' => "6"
    }, selected)
  end

  def options_for_property_type(selected)
    options_for_select({
      'Apartment' => Property::TYPE[:apartment], 
      'Condo' => Property::TYPE[:condo], 
      'House' => Property::TYPE[:house]
    }, selected)
  end

  def options_for_status(selected)
    options_for_select({
      'For Sale' => Property::STATUS[:for_sale], 
      'For Rent' => Property::STATUS[:for_rent]
    }, selected)
  end

  def display_price(property)
    if property.status == Property::STATUS[:for_rent]
      return "#{number_to_currency(property.price / 120)} per month"
    else
      return "#{number_to_currency(property.price)}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'shared/header' %>
  <div id="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
Home!

app/views/properties/_form.html.erb
<%= form_for @property do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :property_type %>
    <%= f.select :property_type, options_for_property_type(@property.property_type) %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, options_for_status(@property.status) %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div>
    <%= f.label :year_built %>
    <%= f.text_field :year_built %>
  </div>

  <div>
    <%= f.label :square_feet %>
    <%= f.text_field :square_feet %>
  </div>

  <div>
    <%= f.label :lot_size %>
    <%= f.text_field :lot_size %>
  </div>

  <div>
    <%= f.label :baths %>
    <%= f.text_field :baths %>
  </div>

  <div>
    <%= f.label :bedrooms %>
    <%= f.text_field :bedrooms %>
  </div>

  <div>
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <%= f.submit 'List Property' %>
<% end %>

app/views/properties/_search.html.erb
<div id="search">
  <%= form_tag request.path, method: :get do %>

    <div>
      <%= label_tag :price_min, 'Price' %>
      <%= text_field_tag :price_min, @search_options[:price_min], class: 'range' %>
      to 
      <%= text_field_tag :price_max, @search_options[:price_max], class: 'range' %>
    </div>

    <div>
      <%= label_tag :beds, 'Beds' %>
      <%= select_tag :beds, bed_options_for_select(@search_options[:beds]) %>
    </div>

    <div>
      <%= label_tag :baths, 'Baths' %>
      <%= select_tag :baths, bath_options_for_select(@search_options[:baths]) %>
    </div>

    <div>
      <%= label_tag :square_feet_min, 'Square Feet' %>
      <%= text_field_tag :square_feet_min, @search_options[:square_feet_min], class: 'range' %>
      to 
      <%= text_field_tag :square_feet_max, @search_options[:square_feet_max], class: 'range' %>
    </div>

    <div>
      <%= label_tag :lot_size_min, 'Lot Size' %>
      <%= text_field_tag :lot_size_min, @search_options[:lot_size_min], class: 'range' %>
      to 
      <%= text_field_tag :lot_size_max, @search_options[:lot_size_max], class: 'range' %>
    </div>

    <div>
      <%= label_tag :year_min, 'Year Built' %>
      <%= text_field_tag :year_min, @search_options[:year_min], class: 'range' %>
      to 
      <%= text_field_tag :year_max, @search_options[:year_max], class: 'range' %>
    </div>

    <%= submit_tag 'Search' %>

  <% end %>
</div>

app/views/properties/_snapshot.html.erb
<div class="property">

  <a href="<%= property_path(property) %>"><img src="<%= property.image_url %>" /></a>

  <div class="name"><%= property.name %></div>

  <div class="price">
    <%= display_price(property) %>
  </div>

  <div class="baths"><%= property.baths %> baths</div>

  <div class="bedrooms"><%= property.bedrooms %> bedrooms</div>

  <div class="year-built">Built <%= property.year_built %></div>

  <div class="square-feet"><%= property.square_feet %> sq. feet</div>

  <div class="lot-size">Lot: <%= property.lot_size %> sq. feet</div>
</div>

app/views/properties/index.html.erb
<%= render partial: 'search' %>

<div id="listings">

  <%= render partial: 'snapshot', collection: @properties, as: :property %>

</div>
<div class="clear"></div>

app/views/properties/new.html.erb
<h2>New Listing</h2>
<%= render partial: 'form' %>

app/views/properties/show.html.erb
<%= render partial: 'search' %>

<div id="listings">

  <%= render partial: 'snapshot', locals: {property: @property} %>

</div>
<div class="clear"></div>

app/views/shared/_header.html.erb
<div id="header">
  <%= link_to 'New Listing', new_property_path, class: 'button' %>
  <%= link_to 'All Listings', properties_path, class: 'button' %>
  <%= link_to 'Rentals', rentals_properties_path, class: 'button' %>
  <%= link_to 'For Sale', for_sale_properties_path, class: 'button' %>
  <%= link_to 'Houses', houses_properties_path, class: 'button' %>
  <%= link_to 'Condos', condos_properties_path, class: 'button' %>
  <%= link_to 'Apartments', apartments_properties_path, class: 'button' %>
  <%= link_to 'Recently Listed', recent_properties_path, class: 'button' %>
</div>

<div id="flash">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
</div>